POST http://localhost:3000/api/contacts
Authorization: Bearer user_2rWmfpe8SizrhnqqRrNbxAo6DUk

{
    "name": "ace",
    "email": "ace@gmail.com",
    "phoneNumber": "",
    "address": ["", ""],
    "userId": "1"
}
